feat: add unified menu, seasons support, and extra player flags

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -4,27 +4,23 @@ version_number="4.16.0-anidb"
 
 # UI
 
-external_menu() {
-    [ "$use_external_menu" = "1" ] && rofi "$1" -sort -dmenu -i -width 1500 -p "$2" "$3"
-    [ "$use_external_menu" = "2" ] && dmenu -l 20 -p "$2"
-}
-
-launcher() {
-    [ "$use_external_menu" = "0" ] && [ -z "$1" ] && set -- "+m" "$2"
-    [ "$use_external_menu" = "0" ] && fzf "$1" --reverse --cycle --prompt "$2"
-    [ "$use_external_menu" = "1" ] && external_menu "$1" "$2" "$external_menu_args"
-    [ "$use_external_menu" = "2" ] && external_menu "$1" "$2"
+menu() {
+    case "$menu_program" in
+        fzf) fzf --reverse --cycle --prompt "$1" $2 $3 ;;
+        rofi) rofi -sort -dmenu -i -p "$1" $2 $3 ;;
+        dmenu) dmenu -p "$1" $3 ;;
+        *) "$menu_program" $3 "$1" ;;
+    esac
 }
 
 nth() {
     stdin=$(cat -)
-    [ -z "$stdin" ] && return 1
+    [ -z "$stdin" ] && exit 1
     line_count="$(printf "%s\n" "$stdin" | wc -l | tr -d "[:space:]")"
     [ "$line_count" -eq 1 ] && printf "%s" "$stdin" | cut -f2,3 && return 0
     prompt="$1"
-    multi_flag=""
-    [ $# -ne 1 ] && shift && multi_flag="$1"
-    line=$(printf "%s" "$stdin" | cut -f1,3 | tr '\t' ' ' | launcher "$multi_flag" "$prompt" | cut -d " " -f 1)
+    [ $# -ne 1 ] && multi_flag="$2"
+    line=$(printf "%s" "$stdin" | cut -f1,3 | tr '\t' ' ' | menu "$prompt" "$multi_flag" "$menu_extra_flags" | cut -d " " -f 1)
     line_start=$(printf "%s" "$line" | head -n1)
     line_end=$(printf "%s" "$line" | tail -n1)
     [ -n "$line" ] || exit 1
@@ -38,6 +34,14 @@ nth() {
 die() {
     printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
     exit 1
+}
+
+info() {
+    printf "\33[2K\r\033[1;34m%s\033[0m\n" "$*"
+}
+
+warn() {
+    printf "\33[2K\r\033[1;33m%s\033[0m\n" "$*" >&2
 }
 
 help_info() {
@@ -86,15 +90,14 @@ help_info() {
         Don't detach the player (useful for in-terminal playback, mpv only)
       --exit-after-play
         Exit the player, and return the player exit code (useful for non interactive scenarios, mpv only)
-      --skip-title <title>
-        Use given title as ani-skip query
+
       -N, --nextep-countdown
         Display a countdown to the next episode
       -U, --update
         Update the script
     Some example usages:
       %s -q 720p banana fish
-      %s --skip --skip-title \"one piece\" -S 2 one piece
+      %s --skip -S 2 one piece
       %s -d -e 2 cyberpunk edgerunners
       %s --batch one piece
       %s --resume -c
@@ -111,15 +114,15 @@ version_info() {
 }
 
 update_script() {
-    printf "[branch:%s] Checking for Update..\n" "$branch"
+    info "[branch:$branch] Checking for Update.."
     update="$(curl --fail-with-body -sL -A "$agent" "https://raw.githubusercontent.com/VVAT3R/ani-cli/$branch/ani-cli")" || die "[branch:$branch] Connection error: $update"
-    printf '%s' "$update" | grep -q "^version_number" || die "[branch:$branch] Invalid Response."
-    update="$(printf '%s\n' "$update" | diff -u "$0" -)"
+    printf "%s" "$update" | grep -q "^version_number" || die "[branch:$branch] Invalid Response."
+    update="$(printf "%s\n" "$update" | diff -u "$0" -)"
     if [ -z "$update" ]; then
-        printf "[branch:%s] Script is up to date :)\n" "$branch"
+        info "[branch:$branch] Script is up to date :)"
     else
-        if printf '%s\n' "$update" | patch "$0" -; then
-            printf "[branch:%s] Script has been updated\n" "$branch"
+        if printf "%s\n" "$update" | patch "$0" -; then
+            info "[branch:$branch] Script has been updated"
         else
             die "[branch:$branch] Can't update for some reason!"
         fi
@@ -134,6 +137,15 @@ dep_ch() {
     done
 }
 
+dep_ch_failover() {
+    [ -z "$1" ] && return 1
+    prog=$(printf "%s" "$1" | cut -d"," -f 1)
+    rest=$(printf "%s" "$1" | cut -s -d"," -f 2-)
+    command -v "$prog" >/dev/null 2>&1 && printf "%s" "$prog" && return 0
+    [ -e "$prog" ] && printf "%s" "$prog" && return 0
+    dep_ch_failover "$rest"
+}
+
 where_iina() {
     [ -e "/Applications/IINA.app/Contents/MacOS/iina-cli" ] && echo "/Applications/IINA.app/Contents/MacOS/iina-cli" && return 0
     printf "%s" "iina" && return 0
@@ -145,8 +157,7 @@ where_mpv() {
 }
 
 cleanup() {
-    [ "$player_function" = "android_mpv" ] && : >"/storage/emulated/0/mpv/mpv.config.mp4"
-    printf "\033[0m"        # clears colors
+    tput sgr0               # clears colors
     rm -f "${histfile}.new" # remove temp logfile
 }
 
@@ -158,7 +169,7 @@ select_quality() {
         worst) result=$(printf "%s" "$links" | grep -E '^[0-9]{3,4}' | tail -n1) ;;
         *) result=$(printf "%s" "$links" | grep -m 1 "$1") ;;
     esac
-    [ -z "$result" ] && printf "Specified quality not found, defaulting to best\n" 1>&2 && result=$(printf "%s" "$links" | head -n1)
+    [ -z "$result" ] && warn "Specified quality not found, defaulting to best" && result=$(printf "%s" "$links" | head -n1)
 
     refr_flag="--referrer=https://anidb.app"
     episode=$(printf "%s" "$result" | cut -d'>' -f2)
@@ -180,7 +191,15 @@ anidb_curl() {
 search_anidb() {
     _query="$(printf '%s' "$1" | sed 's/ /+/g')"
     _page="$(anidb_curl "https://anidb.app/search/suggestions?q=${_query}" -A "$agent" --max-time 10 | tr '\n' ' ' | sed 's/<a href/\n<a href/g')"
-    printf '%s' "$_page" | sed -nE 's|.*anime/[a-z0-9-]+-([0-9]+)".*alt="([^"]+)".*|\1\t\2|p'
+    printf '%s' "$_page" | sed -nE 's|.*anime/([a-z0-9-]+-[0-9]+)".*alt="([^"]+)".*|\1\t\2|p'
+}
+
+anidb_desc() {
+    _anime_link="$1"
+    _page="$(anidb_curl "https://anidb.app/anime/${_anime_link}" -A "$agent" --max-time 10 | tr '\n' ' ' | sed 's|<a href|\n<a href|g')"
+    mal_id="$(printf "%s" "$_page" | sed -nE 's|.*https://myanimelist.net/anime/([0-9]+)/.*|\1|p')"
+    seasons="$(printf "%s" "$_page" | sed -n '/>Seasons</,/>Details</p' | sed -nE 's|.*anime/([^"]+-[0-9]+)"[^>]*title="([^"]+)".*|\1\t\2|p')"
+    [ -n "$seasons" ] && seasons_option="\nseasons"
 }
 
 episodes_list_anidb() {
@@ -323,7 +342,7 @@ play_episode() {
     _resume_pos=""
     if [ "$resume_enabled" = 1 ]; then
         _resume_pos=$(resume_episode "$id")
-        [ -n "$_resume_pos" ] && [ "$_resume_pos" != "0" ] && printf "\33[2K\r\033[1;33mResuming from %s seconds...\033[0m\n" "$_resume_pos" 1>&2
+        [ -n "$_resume_pos" ] && [ "$_resume_pos" != "0" ] && warn "Resuming from $_resume_pos seconds..."
     fi
 
     # mpv socket for position tracking
@@ -345,33 +364,33 @@ play_episode() {
             [ -n "$_mpv_socket" ] && _mpv_args="--input-ipc-server=$_mpv_socket"
             [ -n "$_resume_pos" ] && [ "$_resume_pos" != "0" ] && _mpv_args="$_mpv_args --start=$_resume_pos"
             if [ "$no_detach" = 0 ]; then
-                nohup $player_function $_mpv_args $skip_flag --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" "$episode" $refr_flag >/dev/null 2>&1 &
+                nohup $player_function $_mpv_args $skip_flag --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" "$episode" $refr_flag $player_extra_flags >/dev/null 2>&1 &
             else
-                $player_function $_mpv_args $skip_flag $refr_flag --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" "$episode"
+                $player_function $_mpv_args $skip_flag $refr_flag --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" "$episode" $player_extra_flags
                 mpv_exitcode=$?
                 [ "$exit_after_play" = 1 ] && [ -z "$range" ] && exit "$mpv_exitcode"
             fi
             ;;
-        android_mpv) "$player_function" "$episode" "${anime_title}Episode ${ep_no}" "--tls-verify=no $refr_flag" 2>&1 & ;;
-        android_vlc) nohup am start --user 0 -a android.intent.action.VIEW -d "$episode" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${anime_title}Episode ${ep_no}" >/dev/null 2>&1 & ;;
+        android_mpv) "$player_function" "$episode" "${anime_title}Episode ${ep_no}" "--tls-verify=no $refr_flag" $player_extra_flags 2>&1 & ;;
+        android_vlc) nohup am start --user 0 -a android.intent.action.VIEW -d "$episode" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${anime_title}Episode ${ep_no}" $player_extra_flags >/dev/null 2>&1 & ;;
         *iina*)
             [ -n "$refr_flag" ] && refr_flag="--mpv-${refr_flag#--}"
             if pgrep -f "IINA" >/dev/null 2>&1; then
-                nohup $player_function --no-stdin --mpv-tls-verify=no --mpv-force-media-title="${anime_title}Episode ${ep_no}" $refr_flag "$episode" >/dev/null 2>&1 &
+                nohup $player_function --no-stdin --mpv-tls-verify=no --mpv-force-media-title="${anime_title}Episode ${ep_no}" $refr_flag "$episode" $player_extra_flags >/dev/null 2>&1 &
             else
-                nohup $player_function --no-stdin --mpv-tls-verify=no --keep-running --mpv-force-media-title="${anime_title}Episode ${ep_no}" $refr_flag "$episode" >/dev/null 2>&1 &
+                nohup $player_function --no-stdin --mpv-tls-verify=no --keep-running --mpv-force-media-title="${anime_title}Episode ${ep_no}" $refr_flag "$episode" $player_extra_flags >/dev/null 2>&1 &
             fi
             ;;
-        flatpak_mpv) flatpak run io.mpv.Mpv --input-ipc-server="$_mpv_socket" --start="$_resume_pos" --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" "$episode" $refr_flag >/dev/null 2>&1 & ;;
-        vlc*) nohup $player_function --http-referrer="${refr_flag#--referrer=}" --play-and-exit --meta-title="${anime_title}Episode ${ep_no}" "$episode" >/dev/null 2>&1 & ;;
-        *yncpla*) nohup $player_function "$episode" -- --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" $refr_flag >/dev/null 2>&1 & ;;
-        download) "$player_function" "$episode" "${anime_title}Episode ${ep_no}" ;;
-        catt) nohup catt cast "$episode" >/dev/null 2>&1 & ;;
+        flatpak_mpv) flatpak run io.mpv.Mpv --input-ipc-server="$_mpv_socket" --start="$_resume_pos" --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" "$episode" $refr_flag $player_extra_flags >/dev/null 2>&1 & ;;
+        vlc*) nohup $player_function --http-referrer="${refr_flag#--referrer=}" --play-and-exit --meta-title="${anime_title}Episode ${ep_no}" "$episode" $player_extra_flags >/dev/null 2>&1 & ;;
+        *yncpla*) nohup $player_function "$episode" $player_extra_flags -- --tls-verify=no --force-media-title="${anime_title}Episode ${ep_no}" $refr_flag >/dev/null 2>&1 & ;;
+        download) "$player_function" "$episode" "${anime_title}Episode ${ep_no}" $player_extra_flags ;;
+        catt) nohup catt cast "$episode" $player_extra_flags >/dev/null 2>&1 & ;;
         iSH)
             printf "\e]8;;vlc://%s\a~~~~~~~~~~~~~~~~~~~~\n~ Tap to open VLC ~\n~~~~~~~~~~~~~~~~~~~~\e]8;;\a\n" "$episode"
             sleep 5
             ;;
-        *) nohup $player_function "$episode" >/dev/null 2>&1 & ;;
+        *) nohup $player_function "$episode" $player_extra_flags >/dev/null 2>&1 & ;;
     esac
     replay="$episode"
     unset episode
@@ -387,8 +406,7 @@ play_episode() {
     esac
 
     update_history "$_final_pos"
-    [ "$use_external_menu" = "1" ] && wait
-    [ "$use_external_menu" = "2" ] && wait
+    wait
 }
 
 play() {
@@ -423,7 +441,7 @@ play() {
                     continue
                 fi
             else
-                printf "\33[2K\r\033[1;34mPlaying episode %s...\033[0m\n" "$ep_no"
+                info "Playing episode $ep_no..."
             fi
             [ "$i" = "$end" ] && unset range
             play_episode
@@ -451,14 +469,16 @@ case "$(uname -a | cut -d " " -f 1,3-)" in
     *) player_function="${ANI_CLI_PLAYER:-$(where_mpv)}" ;;           # Linux OS
 esac
 
+player_extra_flags="${ANI_CLI_PLAYER_FLAGS:-}"
 no_detach="${ANI_CLI_NO_DETACH:-0}"
 exit_after_play="${ANI_CLI_EXIT_AFTER_PLAY:-0}"
-use_external_menu="${ANI_CLI_EXTERNAL_MENU:-0}"
-external_menu_normal_window="${ANI_CLI_EXTERNAL_MENU_NORMAL_WINDOW:-0}"
 skip_intro="${ANI_CLI_SKIP_INTRO:-0}"
-skip_title="${ANI_CLI_SKIP_TITLE:-}"
-[ -t 0 ] || { command -v dmenu >/dev/null 2>&1 && use_external_menu=2; }
-[ -t 0 ] || { command -v rofi >/dev/null 2>&1 && use_external_menu=1; }
+menu_program="${ANI_CLI_MENU:-fzf}"
+menu_extra_flags="${ANI_CLI_MENU_FLAGS:-}"
+
+[ -t 0 ] || { command -v rofi >/dev/null 2>&1 && menu_program=rofi; }
+[ -t 0 ] || { command -v dmenu >/dev/null 2>&1 && menu_program=dmenu; }
+
 hist_dir="${ANI_CLI_HIST_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/ani-cli}"
 [ ! -d "$hist_dir" ] && mkdir -p "$hist_dir"
 histfile="$hist_dir/ani-hsts"
@@ -531,14 +551,9 @@ while [ $# -gt 0 ]; do
         --dub) mode="dub" ;;
         --no-detach) no_detach=1 ;;
         --exit-after-play) exit_after_play=1 && no_detach=1 ;;
-        --rofi) use_external_menu=1 ;;
-        --dmenu) use_external_menu=2 ;;
+        --rofi) menu_program=rofi ;;
+        --dmenu) menu_program=dmenu ;;
         --skip) skip_intro=1 ;;
-        --skip-title)
-            [ $# -lt 2 ] && die "missing argument!"
-            skip_title="$2"
-            shift
-            ;;
         -N | --nextep-countdown) search=nextep ;;
         -U | --update)
             branch="${2:-$branch}"
@@ -548,21 +563,21 @@ while [ $# -gt 0 ]; do
     esac
     shift
 done
-[ "$use_external_menu" = "0" ] && multi_selection_flag="${ANI_CLI_MULTI_SELECTION:-"-m"}"
-[ "$use_external_menu" = "1" ] && multi_selection_flag="${ANI_CLI_MULTI_SELECTION:-"-multi-select"}"
-[ "$external_menu_normal_window" = "1" ] && external_menu_args="-normal-window"
+[ "$menu_program" = "fzf" ] && menu_multi_flag="-m"
+[ "$menu_program" = "rofi" ] && menu_multi_flag="-multi-select"
 
-printf "\033[1;34mUsing provider: anidb\033[0m\n" 1>&2
+info "Using provider: anidb"
 
-printf "\33[2K\r\033[1;34mChecking dependencies...\033[0m\n"
-dep_ch "curl" "sed" "grep" || true
-[ "$skip_intro" = 1 ] && (dep_ch "ani-skip" || true)
-
-dep_ch "fzf" || true
+info "Checking dependencies..."
+dep_ch "curl"
+dep_ch "sed"
+dep_ch "grep"
+[ "$skip_intro" = 1 ] && dep_ch "ani-skip"
+dep_ch "$menu_program"
 case "$player_function" in
     debug) ;;
-    download) dep_ch "ffmpeg" "aria2c" ;;
-    android*) printf "\33[2K\rChecking of players on Android is disabled.\nANI-CLI recommends Android MPV for full compatibility.\nAdd:\n include='/storage/emulated/0/mpv/mpv.config.mp4'\nto:\n MPV > Settings > Advanced > mpv.conf\nfor full functionality.\nIgnore, If Done.\n" ;;
+    download) dep_ch_failover "yt-dlp,ffmpeg" >/dev/null || die 'Neither yt-dlp nor ffmpeg found' ;;
+    android*) printf "\33[2K\rChecking of players on Android is disabled.\n" ;;
     *iSH*) printf "\33[2K\rChecking of players on iOS is disabled\n" ;;
     mpv|flatpak_mpv) dep_ch "$player_function" "socat" ;;
     *) dep_ch "$player_function" ;;
@@ -587,33 +602,35 @@ case "$search" in
         printf "%s" "$anime_list" | grep "$id" | cut -f2 | grep -q "(up to date)" && time_until_next_ep "$anime_title"
         ;;
     *)
-        if [ "$use_external_menu" = "0" ]; then
+        if [ "$menu_program" = "fzf" ]; then
             while [ -z "$query" ]; do
                 printf "\33[2K\r\033[1;36mSearch anime: \033[0m" && read -r query
             done
         else
-            [ -z "$query" ] && query=$(printf "" | external_menu "" "Search anime: " "$external_menu_args")
+            [ -z "$query" ] && query=$(: | menu "Search anime: " "" "$menu_extra_flags")
             [ -z "$query" ] && exit 1
         fi
         # for checking new releases by specifying anime name
         [ "$search" = "nextep" ] && time_until_next_ep "$query"
 
         query=$(printf "%s" "$query" | sed "s| |+|g")
+
         anime_list=$(search_anidb "$query")
         [ -z "$anime_list" ] && die "No results found!"
         # check if -i index is a valid number, if so skip interactive selection
         [ "$index" -eq "$index" ] 2>/dev/null && result=$(printf "%s" "$anime_list" | sed -n "${index}p")
         [ -z "$index" ] && result=$(printf "%s" "$anime_list" | nl -w 2 | sed 's/^[[:space:]]//' | nth "Select anime: ")
-        [ -z "$result" ] && exit 1
-        title=$(printf "%s" "$result" | cut -f2)
+        [ -z "$result" ] && die "Invalid/No Anime Selection"
+        title="$(printf "%s" "$result" | cut -f2)"
         anime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
-        id=$(printf "%s" "$result" | cut -f1)
+        id="$(printf "%s" "$result" | cut -f1 | grep -Eo '[0-9]+$')"
+        anidb_desc "$(printf "%s" "$result" | cut -f1)" || true
         ep_list=$(episodes_list_anidb "$id")
-        [ -z "$ep_no" ] && ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$multi_selection_flag")
-        [ -z "$ep_no" ] && exit 1
+        [ -n "$ep_no" ] && [ "$ep_no" -ne -1 ] && printf "%s" "$ep_list" | grep -v -q "^$ep_no$" && die "Invalid Episode Selection"
+        [ -z "$ep_no" ] && ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$menu_multi_flag")
+        [ -z "$ep_no" ] && die "Invalid/No Episode Selection"
         ;;
 esac
-[ "$skip_intro" = 1 ] && mal_id="$(ani-skip -q "${skip_title:-${title}}")"
 
 # moves the cursor up one line and clears that line
 tput cuu1 && tput el
@@ -625,14 +642,25 @@ play
 [ "$player_function" = "download" ] && exit 0
 [ "$player_function" = "debug" ] && exit 0
 
-while cmd=$(printf "next\nreplay\nprevious\nselect\nchange_quality\nquit" | nth "Playing episode $ep_no of $title... "); do
+while cmd=$(printf "next\nreplay\nprevious\nselect${seasons_option}\nchange_quality\nquit" | nth "Playing episode $ep_no of $title... "); do
     case "$cmd" in
         next) ep_no=$(printf "%s" "$ep_list" | sed -n "/^${ep_no}$/{n;p;}") 2>/dev/null ;;
         replay) episode="$replay" ;;
         previous) ep_no=$(printf "%s" "$ep_list" | sed -n "/^${ep_no}$/{g;1!p;};h") 2>/dev/null ;;
-        select) ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$multi_selection_flag") ;;
+        select) ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$menu_multi_flag") ;;
+        seasons)
+            new_anime="$(printf "%s" "$seasons" | nl -w 2 | sed 's/^[[:space:]]//' | nth "Select anime: ")"
+            [ -z "$new_anime" ] && die "Invalid/No Anime Selection"
+            title="$(printf "%s" "$new_anime" | cut -f2)"
+            anime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
+            id="$(printf "%s" "$new_anime" | cut -f1 | grep -Eo '[0-9]+$')"
+            ep_list=$(episodes_list_anidb "$id")
+            ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$menu_multi_flag")
+            [ -z "$ep_no" ] && die "Invalid/No Episode Selection"
+            ;;
         change_quality)
-            new_quality="$(printf "%s" "$links" | launcher | cut -d\> -f1)"
+            new_quality="$(printf "%s" "$links" | menu | cut -d">" -f1)"
+            [ -z "$new_quality" ] && die "No quality selected"
             select_quality "$new_quality"
             ;;
         *)
